model:
  name: "Walmart_DLinear_Localized"
  params:
    seq_len: 52          
    pred_len: 43         
    learning_rate: 0.001 
    max_epochs: 25       
    batch_size: 256      
data:
  split_date: "2012-01-01"