data:
  split_date: "2012-01-01"
model:
  params:
    seq_len: 12
    pred_len: 43
ensemble:
  search_space:
    - {xgb: 0.4, lgb: 0.1, nn: 0.5}
    - {xgb: 0.3, lgb: 0.2, nn: 0.5}
    - {xgb: 0.4, lgb: 0.2, nn: 0.4}
    - {xgb: 0.3, lgb: 0.1, nn: 0.6}
