data:
  split_date: "2012-04-01"

ensemble:
  search_space:
    - {xgb: 1.00, lgb: 0.00}
    - {xgb: 0.90, lgb: 0.10}
    - {xgb: 0.80, lgb: 0.20}
    - {xgb: 0.70, lgb: 0.30}
    - {xgb: 0.60, lgb: 0.40}
    - {xgb: 0.50, lgb: 0.50}
    - {xgb: 0.40, lgb: 0.60}
    - {xgb: 0.30, lgb: 0.70}
    - {xgb: 0.20, lgb: 0.80}
    - {xgb: 0.10, lgb: 0.90}
    - {xgb: 0.00, lgb: 1.00}