model:
  name: "Walmart_TFT"
  params:
    input_size: 52
    hidden_size: 32
    n_head: 2
    max_steps: 200
    scaler_type: "robust"
    start_padding_enabled: true
    random_seed: 42
data:
  split_date: "2012-01-01"
